# Generated by Django 2.2.14 on 2020-08-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=11, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮编')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='联系人电话')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
    ]
